name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Create profiles.yml
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          mkdir -p ~/.dbt
          echo "horrorland:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                warehouse: $SNOWFLAKE_WAREHOUSE
                database: $SNOWFLAKE_DATABASE
                schema: $SNOWFLAKE_SCHEMA
                threads: 1
                client_session_keep_alive: False" > ~/.dbt/profiles.yml

      - name: Run dbt debug
        run: dbt debug --project-dir horrorland

      - name: Run dbt dependencies
        run: dbt deps --project-dir horrorland

      - name: Run dbt build
        run: dbt build --project-dir horrorland
